apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: anil-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/asonmez/anil-operator-catalog:1.0.0
  displayName: Anil Operators
  publisher: Anil Sonmez
  updateStrategy:
    registryPoll: 
      interval: 60m
